// ── Static demo data for all pages ──────────────────────────────────────────
// Used on Vercel/static deployments where the base44 backend is unavailable.

export const DEMO_PROFESSIONALS = [
  {
    id: "pro-1",
    slug: "sarah-mitchell",
    full_name: "Sarah Mitchell",
    title: "Chartered Tax Adviser",
    bio: "CTA-qualified specialist with 14 years focused on corporate and personal tax planning. Particular expertise in R&D credits and cross-border tax structures for UK tech companies.",
    specialisations: ["Corporation Tax", "R&D Tax Credits", "Tax Planning", "Self Assessment"],
    qualifications: ["CTA", "ACA"],
    industries: ["Technology", "Professional Services", "Financial Services"],
    software_expertise: ["Xero", "IRIS", "QuickBooks"],
    hourly_rate: 125,
    location: "London",
    years_experience: 14,
    completed_jobs: 87,
    availability: "available",
    remote_work: true,
    created_date: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: "pro-2",
    slug: "james-thompson",
    full_name: "James Thompson",
    title: "Chartered Accountant — R&D Specialist",
    bio: "ACA qualified with over 10 years experience helping innovative companies claim R&D tax reliefs. Previously at a Big 4 firm; now offering the same expertise at competitive rates.",
    specialisations: ["R&D Tax Credits", "Corporation Tax", "Audit", "Tax Planning"],
    qualifications: ["ACA", "CTA"],
    industries: ["Technology", "Manufacturing", "Life Sciences"],
    software_expertise: ["Sage", "Xero", "CCH"],
    hourly_rate: 110,
    location: "Manchester",
    years_experience: 10,
    completed_jobs: 62,
    availability: "available",
    remote_work: true,
    created_date: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: "pro-3",
    slug: "priya-patel",
    full_name: "Priya Patel",
    title: "ACCA Accountant — VAT & Bookkeeping",
    bio: "Experienced ACCA professional specialising in cloud bookkeeping, Making Tax Digital, and VAT compliance for SMEs. Xero Certified Advisor. Available for ongoing retainer or one-off projects.",
    specialisations: ["VAT", "Bookkeeping", "Making Tax Digital", "Payroll"],
    qualifications: ["ACCA", "AAT"],
    industries: ["Retail", "E-commerce", "Hospitality"],
    software_expertise: ["Xero", "QuickBooks", "FreeAgent"],
    hourly_rate: 65,
    location: "Birmingham",
    years_experience: 7,
    completed_jobs: 134,
    availability: "available",
    remote_work: true,
    created_date: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  {
    id: "pro-4",
    slug: "david-chen",
    full_name: "David Chen",
    title: "Tax Consultant — Self Assessment & CGT",
    bio: "ATT and ACCA qualified with a focus on personal tax, including self assessment, capital gains, and inheritance tax planning. Particular experience with property investors and high-net-worth individuals.",
    specialisations: ["Self Assessment", "Capital Gains", "Tax Planning", "VAT"],
    qualifications: ["ACCA", "ATT"],
    industries: ["Property", "Financial Services", "Private Clients"],
    software_expertise: ["TaxCalc", "Xero", "QuickBooks"],
    hourly_rate: 85,
    location: "Leeds",
    years_experience: 9,
    completed_jobs: 98,
    availability: "limited",
    remote_work: true,
    created_date: new Date(Date.now() - 4 * 86400000).toISOString(),
  },
  {
    id: "pro-5",
    slug: "emma-roberts",
    full_name: "Emma Roberts",
    title: "Payroll Specialist & Bookkeeper",
    bio: "AAT qualified payroll and bookkeeping professional with 8 years running payroll for companies of 5 to 250 employees. CIPP-educated. Expert in RTI, auto-enrolment, and HMRC compliance.",
    specialisations: ["Payroll", "Bookkeeping", "Making Tax Digital"],
    qualifications: ["AAT"],
    industries: ["Healthcare", "Retail", "Hospitality", "Professional Services"],
    software_expertise: ["BrightPay", "Xero", "Sage Payroll", "QuickBooks"],
    hourly_rate: 50,
    location: "Bristol",
    years_experience: 8,
    completed_jobs: 211,
    availability: "available",
    remote_work: true,
    created_date: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: "pro-6",
    slug: "michael-obrien",
    full_name: "Michael O'Brien",
    title: "Tax Investigation Specialist",
    bio: "Former HMRC Inspector now assisting businesses and individuals facing tax investigations, enquiries and compliance checks. ACA and CTA qualified. No case too complex.",
    specialisations: ["Tax Planning", "Corporation Tax", "Self Assessment", "VAT"],
    qualifications: ["ACA", "CTA"],
    industries: ["Construction", "Professional Services", "Private Clients"],
    software_expertise: ["IRIS", "CCH", "TaxCalc"],
    hourly_rate: 145,
    location: "Edinburgh",
    years_experience: 18,
    completed_jobs: 43,
    availability: "available",
    remote_work: true,
    created_date: new Date(Date.now() - 6 * 86400000).toISOString(),
  },
];

export const DEMO_JOBS = [
  {
    id: "job-1",
    title: "Self Assessment Tax Return 2023/24",
    description: "I need my personal self assessment completed for the 2023/24 tax year. I'm employed full-time and also have rental income from one buy-to-let property. All records are prepared including P60, rental statements and bank records.",
    category: "tax_return",
    budget_type: "fixed",
    budget_amount: 195,
    location: "Remote",
    remote: true,
    duration: "one_off",
    required_qualifications: ["ACCA", "ACA"],
    status: "open",
    company_name: "Smith Consulting Ltd",
    created_date: new Date(Date.now() - 2 * 3600000).toISOString(),
  },
  {
    id: "job-2",
    title: "Monthly Bookkeeping & VAT Returns",
    description: "Small e-commerce business (£180k annual turnover) requires ongoing monthly bookkeeping and quarterly VAT return filing. Currently using Xero. Looking for a reliable professional for a long-term arrangement.",
    category: "bookkeeping",
    budget_type: "fixed",
    budget_amount: 380,
    location: "Remote",
    remote: true,
    duration: "ongoing",
    required_qualifications: ["AAT", "ACCA"],
    status: "open",
    company_name: "BlueSky Retail Ltd",
    created_date: new Date(Date.now() - 5 * 3600000).toISOString(),
  },
  {
    id: "job-3",
    title: "R&D Tax Credit Claim — Software Startup",
    description: "Our SaaS startup is seeking a CTA-qualified specialist to prepare and submit an R&D tax credit claim for FY2023. We have qualifying expenditure estimated at £240k in software development activities. Technical narrative support required.",
    category: "corporation_tax",
    budget_type: "fixed",
    budget_amount: 1400,
    location: "Remote",
    remote: true,
    duration: "one_off",
    required_qualifications: ["CTA", "ACA"],
    status: "open",
    company_name: "Nexus Software Ltd",
    created_date: new Date(Date.now() - 8 * 3600000).toISOString(),
  },
  {
    id: "job-4",
    title: "Payroll Processing — 12 Employees",
    description: "Looking for a professional to handle monthly payroll for our team of 12 employees. Must include RTI submissions, pension contributions (NEST), P60s and P11Ds at year end. Immediate start preferred.",
    category: "payroll",
    budget_type: "fixed",
    budget_amount: 220,
    location: "Remote",
    remote: true,
    duration: "ongoing",
    required_qualifications: ["AAT", "ACCA"],
    status: "open",
    company_name: "Meridian Health CIC",
    created_date: new Date(Date.now() - 12 * 3600000).toISOString(),
  },
  {
    id: "job-5",
    title: "Corporation Tax Return — Professional Services Firm",
    description: "Annual corporation tax return required for a professional services LLP with turnover of £620k. Accounts are already prepared by our internal team. Need a qualified professional to review and submit CT600.",
    category: "corporation_tax",
    budget_type: "fixed",
    budget_amount: 750,
    location: "Remote",
    remote: true,
    duration: "one_off",
    required_qualifications: ["ACA", "CTA"],
    status: "open",
    company_name: "Harrington Partners LLP",
    created_date: new Date(Date.now() - 18 * 3600000).toISOString(),
  },
  {
    id: "job-6",
    title: "Capital Gains Tax Advice — Property Portfolio",
    description: "I am disposing of two investment properties this tax year and need expert advice on CGT liability, available reliefs, and optimal disposal timing. I also have some unlisted shares to consider.",
    category: "advisory",
    budget_type: "fixed",
    budget_amount: 520,
    location: "Remote",
    remote: true,
    duration: "short_term",
    required_qualifications: ["CTA", "ACCA"],
    status: "open",
    company_name: "Private Client",
    created_date: new Date(Date.now() - 24 * 3600000).toISOString(),
  },
  {
    id: "job-7",
    title: "VAT Registration & First Return",
    description: "Newly VAT-registered limited company (retail & wholesale) needs help completing the first VAT return and setting up proper Xero chart of accounts for VAT tracking. Flat-rate scheme eligibility review also required.",
    category: "vat",
    budget_type: "fixed",
    budget_amount: 165,
    location: "Remote",
    remote: true,
    duration: "one_off",
    required_qualifications: ["ACCA", "AAT"],
    status: "open",
    company_name: "Clearview Supplies Ltd",
    created_date: new Date(Date.now() - 30 * 3600000).toISOString(),
  },
  {
    id: "job-8",
    title: "HMRC Tax Investigation Support",
    description: "Our company has received an HMRC compliance check letter regarding employment status of contractors. We need an experienced tax professional to manage the correspondence, prepare submissions and negotiate on our behalf.",
    category: "advisory",
    budget_type: "fixed",
    budget_amount: 1800,
    location: "Remote",
    remote: true,
    duration: "long_term",
    required_qualifications: ["CTA", "ACA"],
    status: "open",
    company_name: "BuildRight Contractors Ltd",
    created_date: new Date(Date.now() - 36 * 3600000).toISOString(),
  },
  {
    id: "job-9",
    title: "Annual Accounts & CT600 — Small Limited Company",
    description: "Small IT consultancy (sole director, £95k turnover) requires year-end accounts preparation and corporation tax return. All bank statements and invoices available via Xero. First year of trading.",
    category: "corporation_tax",
    budget_type: "fixed",
    budget_amount: 420,
    location: "Remote",
    remote: true,
    duration: "one_off",
    required_qualifications: ["ACCA", "ACA"],
    status: "open",
    company_name: "Apex IT Consulting Ltd",
    created_date: new Date(Date.now() - 48 * 3600000).toISOString(),
  },
  {
    id: "job-10",
    title: "Making Tax Digital — Xero Setup & Migration",
    description: "Established sole trader (£220k turnover) needs to migrate from spreadsheets to Xero ahead of MTD for Income Tax. Requires chart of accounts setup, historical data import, and training session.",
    category: "bookkeeping",
    budget_type: "fixed",
    budget_amount: 280,
    location: "Remote",
    remote: true,
    duration: "short_term",
    required_qualifications: ["ACCA", "AAT"],
    status: "open",
    company_name: "Greenfield Landscaping",
    created_date: new Date(Date.now() - 60 * 3600000).toISOString(),
  },
];

export const DEMO_REVIEWS = [
  {
    id: "rev-1",
    professional_id: "pro-1",
    reviewer_name: "Tom Hargreaves",
    reviewer_company: "Hargreaves Digital Ltd",
    rating: 5,
    comment: "Sarah delivered an exceptional R&D tax credit claim for our software company. She identified qualifying expenditure we'd completely missed and the final claim was significantly higher than expected. Highly professional throughout.",
    service_type: "R&D Tax Credits",
    verified: true,
    created_date: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  {
    id: "rev-2",
    professional_id: "pro-3",
    reviewer_name: "Aisha Kamara",
    reviewer_company: "Bloom Skincare",
    rating: 5,
    comment: "Priya has been our bookkeeper for 8 months now and she's transformed how we manage our finances. VAT returns done on time every quarter, everything in Xero is perfectly reconciled. Can't recommend highly enough.",
    service_type: "Bookkeeping",
    verified: true,
    created_date: new Date(Date.now() - 7 * 86400000).toISOString(),
  },
  {
    id: "rev-3",
    professional_id: "pro-2",
    reviewer_name: "Mark Stevenson",
    reviewer_company: "Innovatech Solutions",
    rating: 5,
    comment: "James handled our R&D claim with complete confidence. The technical narrative he wrote was detailed and compelling — HMRC accepted it first time with no queries. Will be using him again next year.",
    service_type: "R&D Tax Credits",
    verified: true,
    created_date: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
  {
    id: "rev-4",
    professional_id: "pro-4",
    reviewer_name: "Rachel Okonkwo",
    reviewer_company: "Private Client",
    rating: 5,
    comment: "David sorted out a complicated CGT situation involving multiple property disposals and some unlisted shares. Saved me a considerable amount through careful use of available reliefs. Very clear communicator.",
    service_type: "Capital Gains",
    verified: true,
    created_date: new Date(Date.now() - 14 * 86400000).toISOString(),
  },
  {
    id: "rev-5",
    professional_id: "pro-5",
    reviewer_name: "Chris Baldwin",
    reviewer_company: "Baldwin & Sons Catering",
    rating: 5,
    comment: "Emma has been running payroll for our 22-person team for over a year. Never a mistake, always on time, and she sorted our auto-enrolment setup with no fuss. Great value for the service provided.",
    service_type: "Payroll",
    verified: true,
    created_date: new Date(Date.now() - 18 * 86400000).toISOString(),
  },
  {
    id: "rev-6",
    professional_id: "pro-6",
    reviewer_name: "Natasha Brennan",
    reviewer_company: "NB Construction Ltd",
    rating: 5,
    comment: "When we received the HMRC enquiry letter I was genuinely worried. Michael took over immediately, handled all the correspondence and we came out of it with a negligible adjustment. His ex-HMRC background was invaluable.",
    service_type: "Tax Planning",
    verified: true,
    created_date: new Date(Date.now() - 22 * 86400000).toISOString(),
  },
];