/** Raw demo bid templates — shared by My Bids and workspace sync. */
export const DEMO_BID_TEMPLATES = [
  {
    id: "demo-pending",
    project_id: "demo-project-pending",
    project_title: "Self Assessment Tax Return 2023/24",
    amount: 280,
    timeline_label: "Within 3 days",
    status: "pending",
    bidding_deadline: new Date(Date.now() + 18 * 60 * 60 * 1000).toISOString(),
    created_date: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "demo-shortlisted",
    project_id: "demo-project-shortlisted",
    project_title: "Corporation Tax Return — Ltd Company",
    amount: 550,
    timeline_label: "Within 1 week",
    status: "shortlisted",
    bidding_deadline: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    created_date: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "demo-selected",
    project_id: "demo-project-selected",
    project_title: "HMRC Enquiry Support — Director",
    amount: 1200,
    timeline_label: "Within 2 weeks",
    status: "accepted",
    awarded: true,
    bidder_email: "demo-professional@taxprouk.local",
    bidding_deadline: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
    created_date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "demo-rejected",
    project_id: "demo-project-rejected",
    project_title: "Payroll Setup & Processing",
    amount: 180,
    timeline_label: "Ongoing retainer",
    status: "rejected",
    bidding_deadline: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    created_date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
];
